Repository data-exp-lab/yt-napari, pull requests merged in 2023-11, with the labels that each got.

#110 automate schema version naming
  src/yt_napari/_schema_version.py
  src/yt_napari/_tests/_test_json.json
  src/yt_napari/_tests/_test_json_slice.json
  src/yt_napari/_tests/_test_json_timeseries.json
  src/yt_napari/_tests/_test_json_timeseries_stack.json
  src/yt_napari/_tests/test_schema_version_comparisons.py
  src/yt_napari/schemas/_version_comparison.py
Labels: enhancement, CI

#112 updating readme section on running tests
  README.md
Labels: documentation, CI

#108 Update _widget_reader.py
  src/yt_napari/_tests/test_widget_reader.py
  src/yt_napari/_widget_reader.py
Labels: enhancement
